
// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2024 using ChatGPT
// from a file containing the following notice:

/*
 * This material, written by Henry Spencer, was released by him
 * into the public domain and is thus not subject to any copyright.
 */

import Foundation
import shared

@main final class Getopt : ShellCommand {
    
    var args : [String] = []
    var help = false
    
//    optind = 2
//    var argv = CommandLine.arguments
    
//    var c: Int32
    
    func parseOptions() throws(CmdErr) {
      let go = BSDGetopt( CommandLine.arguments[0] )
      go.skip()
      
      while let (ch, optarg) = try go.getopt() {
        switch ch {
        case "?":
          help = true
        default:
          if !optarg.isEmpty {
            print(" -\(ch) \(optarg)", terminator: "")
          } else {
            print(" -\(ch)", terminator: "")
          }
        }
      }
      
      args = go.remaining
    }
    
    func runCommand() throws(CmdErr) {
      print(" --", terminator: "")
      for i in args {
        print(" \(i)", terminator: "")
      }
      print("")
    }
  
  var usage = "getopt optionString [arguments]"
}

