
// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2024 using ChatGPT
// from a file containing the following notice:

/*
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 1991, 1993, 1994
 *  The Regents of the University of California.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

import CMigration

@main final class basename : ShellCommand {
  
  struct CommandOptions {
    var args : [String] = []
    var suffix: String?
  }

  // the actual main function, with the commandline arguments passed in so that testing
  // can invoke the main with mocked command line arguments
  func parseOptions() throws(CmdErr) -> CommandOptions {
    var opts = CommandOptions()
    var aflag = false

    let go = BSDGetopt("as:")
    while let (ch, optarg) = try go.getopt() {
      switch ch {
        case "a":
          aflag = true
        case "s":
          opts.suffix = optarg
        default:
          throw CmdErr(1)
      }
    }

    opts.args = go.remaining

    if opts.args.count < 1 {
      throw CmdErr(1)
    }

    if opts.suffix == nil, !aflag, opts.args.count == 2 {
      opts.suffix = opts.args[1]
      opts.args.removeLast()
    }
    return opts
  }

  func runCommand(_ opts : CommandOptions) {
    for arg in opts.args {
      arg.withCString { vv in
        let vvv = UnsafeMutablePointer(mutating: vv)
        if let pa = Darwin.basename(vvv) {
          let p = String(cString: pa)
          let px = stripSuffix(p, opts.suffix)
          print(px)
        }
      }
    }
  }

  func stripSuffix(_ p : String, _ suffix: String?) -> String {
    guard let suffix,
          p.count > suffix.count,
          p.hasSuffix(suffix) else { return p }
    return String(p.dropLast(suffix.count))
  }

  var usage : String = """
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
"""

}
